# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9c3d1c7bb116af3fdeb622ec276c162846ce6e0e71720c7598add641afa6f1b9612154a7a915fd59b66772eaed186c967be06003dee1e3e4252feddf2d67db42

test:
  secret_key_base: 1313c7a4158deee145edcaf195ebfb58b23484b6adcb074afef1c54a5d2bd2be7ac3b58fae6d5b905b16314756246864b4a561eea604c664190b627543f445a8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
